### ISSUE TITLE
Слежка за героем

### ISSUE THREAD

**Issue by red-led** [standy/the-tale-ext#19]
Было бы неплохо добавить возможность автоматически фокусировать карту на герое

**Comment by catHD** [comment]
widgets.map.CenterOnHero();

`
setInterval(widgets.map.CenterOnHero(),10000);
`
Но тут смысла 0, это же zero-game.

**Comment by red-led** [comment]
Спасибо.

Ну у меня в отдельной вкладке всегда открыто, периодически посматриваю, что он там делает. Смотреть на пустую карту странновато. А если закрыть рсширение не будет работать. Так что уже 0.5-player получается.

**Comment by catHD** [comment]
Пусть @standy решит, нужна ли эта галочка, сделать 10 строк)
