### ISSUE TITLE
Stats

### ISSUE THREAD

**Issue by catHD** [standy/the-tale-ext#29]
Привет.

Есть вопрос по stats:
![2016-04-18_11-27-49](https://cloud.githubusercontent.com/assets/5936445/14597956/aa9dba12-0558-11e6-831a-8785c5238052.png)

![2016-04-18_11-39-19](https://cloud.githubusercontent.com/assets/5936445/14598325/47101402-055a-11e6-933b-47feda7ff477.png)

При пустом hit объекте , hit.count = undefined, и chance = NaN. 

Вот этот NaN, хотя alt показывает кол-во срабатываний, этот NaN идейно тут?

Я бы всё же отображал шанс прохода на 100 ударов к примеру. Завести общий счетчик ударов и вести по нему?

**Comment by standy** [comment]
Это баг, конечно. Видимо в игре что-то поменялось.
Если есть желание исправить ― присылайте PR, выпущу обновление
