### ISSUE TITLE
Парсер действий

### ISSUE THREAD

**Issue by catHD** [standy/the-tale-ext#35]
@standy @Tiendil

Есть ли метод в API сказки или структурированное хранилище для списка "фраз" для действий. Учитывая постоянное добавление фраз в игру, правильно, наверно, было бы добавить какой то (возможно отдельный) парсер фраз.

**Comment by Tiendil** [comment]
Сейчас есть только выгрузка словаря в json. Могу аналогичную сделать для фраз.

**Comment by Tiendil** [comment]
Но это смотря зачем оно надо, с фразами ведь возвращаются дополнительные параметрами. Может в них лучше чего добавить полезного?

**Comment by catHD** [comment]
@Tiendil 

http://the-tale.org/forum/threads/1687?page=37#m183046

Краткая информация по бою. 

здесь: https://github.com/standy/the-tale-ext/blob/master/source/js/parse/journalPhrases.js

Парсер собирает все действия для последующего "сжатия"

> Но это смотря зачем оно надо, с фразами ведь возвращаются дополнительные параметрами. Может в них лучше чего добавить полезного?

Какие есть варианты? Сейчас фразы в логе боя достаточно информативны, но для некоторых они "слишком" информативны.

**Comment by standy** [comment]
Насколько знаю сейчас парсить фразы уже нет смысла, все данные приходят в сообщениях
```
[
  1485278704.4751346,
  "12:58",
  "Че Гевара разбежался, чтобы атаковать, но попал в заранее подготовленную аколитом огня ловушку.",
  280003,
  {
    "attacker": "аколит огня",
    "defender": "Че Гевара",
    "damage": "89"
  }
]
```
Инфа по коду есть в лингвистике http://the-tale.org/linguistics/ 
Например `280003` http://the-tale.org/linguistics/templates/?key=280003

Если бы получить эту инфу в виде json, было бы вообще хорошо
К примеру в апи сказки выдать словарь с id, группой и типом для всех типов фраз

**Comment by Tiendil** [comment]
Да, я про это и говорил.

**Comment by catHD** [comment]
Хм, видимо я не осознал сразу.

@Tiendil 

Мы можем либо парсить приходящее сообщение, если в нём будет "тип", либо получать массив из API и затем сравнивать его с фразой.

**Comment by Tiendil** [comment]
тип и переменные в нём есть

**Comment by catHD** [comment]
@Tiendil 

Идеально бы иметь метод для получения массива с идентификатором типа, описанием, и списком входящих в него фраз.

**Comment by Tiendil** [comment]
Зачем? Тип и параметры возвращаются с каждой фразой в дневнике/журнале.

**Comment by catHD** [comment]
@Tiendil 

А типы "статичны" ? Пополняться не будут? Получив тип хорошо бы ещё понимать что это)

**Comment by Tiendil** [comment]
Типы могут добавляться и удаляться, но менять смысл не будут. Может менятьс перечень переменных в них. В любом случае, каждый тип нужно по-своему обрабатывать, поэтому толку от отдельного метода для автоматического получения всех типов не будет (имхо). Посмотреть какой тип что значит можно так, как standy уже написал чуть выше.

**Comment by catHD** [comment]
Дело в том что когда приходит: 

http://the-tale.org/linguistics/templates/?key=280002

Я знаю что это такое, но когда мне придёт : 

http://the-tale.org/linguistics/templates/?key=280022

Я не смогу понять что это, и откуда оно, и вообще к какой группе его и не конец ли это боя. 

По этому либо придётся спарсить сейчас всю лингвистику, либо ждать API к ней

**Comment by Tiendil** [comment]
http://the-tale.org/linguistics/templates/?key=280022 — такого типа фраз нет

**Comment by catHD** [comment]
Опять на бегу писал, прошу прощения.
Опишу исходную задачу:  Изначально тт собирает статистику по  скилам, мы собираемся отказаться от Парсинга самого сообщения и определять тип действия по идентификатору, но у нас отсутствует соответствие. Т.е на момент разбора я не знаю что такое 280008.
JSON бы устроил, но если в след. обнове добавят действий то парсер опять сломается.  Я прав? Если нет то поправьте

**Comment by Tiendil** [comment]
Если придёт фраза нового типа, его всё равно придётся прописывать в коде (как новую абилку, например). 

Зачем искусственно поддерживать соотношение фраза-тип, если он и так возвращается для каждой фразы? 

Не вижу как полный перечень фраз может быть полезен.

**Comment by catHD** [comment]
@Tiendil 

Я всё ещё не улавливаю каким образом я из кода внутри message должен узнать что 280002 - это "Применение способности «Контроль»."  ?

**Comment by Tiendil** [comment]
Никаким.

Соответсвие надо поддерживать вручную. И его и так поддерживают — сейчас тип фразы захардкожен в каждом её примере (https://github.com/standy/the-tale-ext/blob/master/source/js/parse/journalPhrases.js).

Экспорт фраз из игры никак с этим не поможет. 

Но, поскольку тип фразы и её параметры теперь возвращаются вместе с ней, то не надо поддерживать сам список фраз, достаточно поддерживать список типов и реакций на них (что сейчас и так делается).

**Comment by catHD** [comment]
@Tiendil 

Отлично, мы пришли к пониманию, наконец. 

> достаточно поддерживать список типов и реакций на них

Для этого я и прошу JSON/API метод, что бы сейчас получить список соответствия.

 `280002 - Способность Контроль`

А дальше уже при возникновение ситуации когда код будет не известен, просто производить "ручное" добавление.

Как Вам такая реализация ?

**Comment by Tiendil** [comment]
Так а смысл? Появился новый тип — зашли посмотреть на сайте, прочитали, сделали соответствующее изменение в расширении.

Автоматически при появлении нового типа всё равно ничего сделать неполучится. Они в большинстве своём уникальны.

**Comment by catHD** [comment]
@Tiendil 

Хорошо, выкинем идею с API.

Сейчас JSON того что есть можно получить ?)

**Comment by Tiendil** [comment]
Объясни зачем, я не понимаю какую автоматическую работу ты хочешь с ним сделать.

**Comment by catHD** [comment]
> Объясни зачем, я не понимаю какую автоматическую работу ты хочешь с ним сделать.

Имея сейчас хотя бы соответствие 'code' - 'название', я смогу присвоить записи нужный "тип", была ли использована ли способность, или это был просто удар или это вообще лут. Так же будет возможность считать, сколько раз использовалась та или другая способность.

Если соответствия не будет ,мне придется каждый раз лазить в : 

http://the-tale.org/linguistics/templates/?key=XXX

Парсить от туда `<h3>Тип: Журнал: Удар</h3>`

И делать свой файл соответствия, что бы не плодить 100500 запросов от каждого из клиентов который использует расширение.

**Comment by Tiendil** [comment]
Вот идентификаторы текущий типов (из ближайшего обновления) и их названий: http://pastebin.com/4GF3Jp3y

Хотя всё равно не понимаю почему именно в JSON и что с этим будет делаться. Всё равно в коде **придётся руками прописать**, что фраза типа X обозначает Y и реагировать на неё надо действием Z.

**Comment by catHD** [comment]
Отлично. Благодар. Сейчас 550 эл-тов.

На будущее: Об изменение типов добавление/удаление, читать из CHANGELOG?

**Comment by Tiendil** [comment]
Сейчас изменения я записываю тут: https://github.com/Tiendil/the-tale/tree/master/release_news

Но явно про новые типы там может быть и не указано. Постраюсь не забывать там пометки по фразам делать.

**Comment by standy** [comment]
@Tiendil За список спасибо!
Хотелось бы ещё получать это методом из апи, и иметь разбивку по группам, как здесь: http://the-tale.org/linguistics/

Это позволит расширению не ломаться при появлении новых типов, к примеру если добавится новая способность можно подписать текстом из апи, и (главное) вывести в статистике боя

**Comment by catHD** [comment]
@standy 

https://gist.github.com/catHD/f6dedddf80d9fd2e1f6e3b06600b5935

Есть вариант ещё получать "ожидаемые параметры" и доставать парсером просто передавая в hover если отсутствует действие по умолчанию для данного типа.

**Comment by catHD** [comment]
@standy 

Нужна помощь по группировке типов событий. Сейчас в расширение самих типов действия явно меньше :( Может их как то скомпоновать или расширить?

Как я себе это вижу: из json выше выбираем ID типа, они "скомпонованы" по группам типов в логике расширения. Дальше, по той же логики что и сейчас, отрисовываем значки и т.п.

**Comment by Tiendil** [comment]
>Это позволит расширению не ломаться при появлении новых типов, к примеру если добавится новая способность можно подписать текстом из апи
Я бы не завязывался сильно на группы, сегодня группа есть, завтра нет. Фразы могут перемещаться между ними.

Но пожелание по API учту. В принципе, push request всегда можно сделать :-)

**Comment by standy** [comment]
Готово с #39.
Добавление фраз в расширение выглядит примерно так: https://github.com/standy/the-tale-ext/blob/master/source/js/utils/act/act-fight.ts

Скрин из новой вкладки расширения:
![image](https://cloud.githubusercontent.com/assets/750319/24082422/4d8f4800-0cd6-11e7-885a-f300b7a35d27.png)
