### ISSUE TITLE
REGION

### ISSUE THREAD

**Issue by catHD** [standy/the-tale-ext#36]
Request URL:http://the-tale.org/game/map/region-14466241-1486472671.696258?_=1486475506618

Раздел map видимо изменился в 0.3.24

`
{status: "error", code: "common.404", error: "Извините, запрашиваемая Вами страница не найдена."}
`

Что вызывает ошибку токена.  

Сейчас любой запрос который получит 404 - убьет токен

_update:_
Правильный формат : 

Request URL:http://the-tale.org/game/map/api/region?api_client=the_tale-v0.3.24.2&amp;api_version=0.1&_=1486476062640

**Comment by catHD** [comment]
Но наверно надо делать 0.4.9.1 , а в 0.5.0 выпускать полную обнову типов и парсера :)

**Comment by standy** [comment]
Готово
