### ISSUE TITLE
Авто-выбор в заданиях: использовать option_uid вместо choiceName.

### ISSUE THREAD

**Issue by multlurk** [standy/the-tale-ext#48]
Предлагаю использовать option_uid вместо choiceName.
option_uid выглядит примерно так - #option([ns-1]finish_spying_choice, [ns-1]blackmail_finish, blackmail).
Свойство "blackmail" -  путь (тип пути), по которому будет выполняться задание.
В игре используется генератор квестов https://github.com/Tiendil/questgen .
Влияние выбора на характер можно посмотреть в репозитории questgen.

Думаю, option-uid актуальнее чем описание выбора.

**Comment by multlurk** [comment]
Изменения в коде сделал. Чтоб проверить работу жду, пока попадется задание с доступным выбором.

**Comment by Nilsden** [comment]
Стоит перейти к этому варианту, т.к. в текущей реализации появление новых фраз в лингвистике приводит к тому, что эти фразы не распознаются, и автовыбор не срабатывает. Плюс ко всему, появились фразы выбора, в которых используется имя НПС: 

> рассказать Светлозаре всю правду

> узнать о Кворин всё, что можно

Писать ради таких фраз отдельный обработчик нерационально.

 По третьему "значению" из option_uid действительно можно определить, в какую сторону изменится честь или миролюбие.
