### ISSUE TITLE
Отсутсвие моба приводит к падению

### ISSUE THREAD

**Issue by catHD** [standy/the-tale-ext#52]
Нужна обработка случаев когда моба нет в базе ext
![2017-06-22 10-24-32](https://user-images.githubusercontent.com/5936445/27421977-4327d3ce-5735-11e7-9250-078ae132e8d8.png)

**Comment by catHD** [comment]
Небольшой фикс против падения #53 , но нужен нормальных механизм обновления базы мобов. 

@standy еженедельный релиз новой версии ? >_<

**Comment by standy** [comment]
Может быть данные по мобам есть в каком-нибудь апи?

**Comment by catHD** [comment]
Здесь ничего http://the-tale.org/guide/api

Если только грабить http://the-tale.org/guide/mobs/
